### ISSUE TITLE
configure: error: no usable spandsp

### ISSUE THREAD

**Issue by n8twj** [freeswitch/mod_unimrcp#12]
Following the build instructions, freeswitch complains:

`checking for spandsp >= 3.0... configure: error: no usable spandsp; please install spandsp3 devel package or equivalent`

**Comment by andywolk** [comment]
try installing spandsp from the FreeSWITCH repo or from source.

**Comment by TheMyth42** [comment]
HI - i am following build instructions in README in this repo

**Comment by n8twj** [comment]
HI - i am following build instructions in README in this repo

**Comment by seven1240** [comment]
PR is welcome to update README or fix anything.

The README was based an older version of spandsp. unfortunately the spandsp lib is actively developed in the master branch and doesn't has stable release or version tags. You can find hint from https://github.com/signalwire/freeswitch/issues/2248

And vote on https://github.com/freeswitch/spandsp/issues/13 might also help.
