### ISSUE TITLE
How to build an ARM64 docker image for mod_unimrcp?

### ISSUE THREAD

**Issue by ivenlau** [freeswitch/mod_unimrcp#3]
I followed the ReadMe to write one Dockerfile to build docker image in ARM64 machine, but it always occured error like this: 

`checking for freeswitch... no
configure: error: Package requirements (freeswitch) were not met:
No package 'freeswitch' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables FREESWITCH_CFLAGS
and FREESWITCH_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
The command '/bin/sh -c cd /mod_unimrcp &&    export PKG_CONFIG_PATH=/usr/local/freeswitch/libs/pkgconfig:/usr/local/unimrcp/libs/pkgconfig &&     ./bootstrap.sh &&     ./configure &&     make &&     make install' returned a non-zero code: 1`

So how can I get the correct steps to build one ARM64 image?

**Comment by seven1240** [comment]
```
docker run -it debian:11 bash
```

Then following the procedure in README. When you make sure all your procedure works, you can turn that into a Dockerfile.

Please go to https://forum.signalwire.community/ to ask questions. Only report here when you think it's a bug.
