### ISSUE TITLE
mod_unimrcp canot use in centos7.9

### ISSUE THREAD

**Issue by linggood** [freeswitch/mod_unimrcp#6]
I use these command,

> $ git clone https://github.com/freeswitch/mod_unimrcp.git
> $ cd mod_unimrcp
> $ export PKG_CONFIG_PATH=/usr/local/freeswitch/lib/pkgconfig:/usr/local/unimrcp/lib/pkgconfig
> $ ./bootstrap.sh
> $ ./configure
> $ make
> $ sudo make install
> $ cd ..

It show that:

> checking for FREESWITCH... no
> configure: error: Package requirements (freeswitch) were not met:
> 
> No package 'freeswitch' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.

how could i use it

**Comment by seven1240** [comment]
you should install FreeSWITCH first

**Comment by linggood** [comment]
FreeSWITCH has been installed by “yum install ***”，now it without mod_unimrcp， so I just want install mod_unimrcp
