### ISSUE TITLE
How to build UniMRCP if FreeSWITCH deps are installed from packages?

### ISSUE THREAD

**Issue by hheedfeld** [freeswitch/mod_unimrcp#7]
Hi,

I built FreeSWITCH from source with FreeSWITCH deps installed from packages (`apt-get build-dep freeswitch`).

When building UniMRCP, configure does not find libsofia-sip-ua.

How can I solve this?

Thanks,
Henning

**Comment by seven1240** [comment]
what's your FreeSWITCH version? what's your OS ? do you have some logs? it's hard to guess what's your problem.
