### ISSUE TITLE
nstallation Error Help

### ISSUE THREAD

**Issue by zanmeipaul** [freeswitch/mod_unimrcp#8]
This error is reported when executing unimrcp configuration according to the installation process. How to solve it？

configure: Sofia SIP library configuration
checking for Sofia-SIP... configure: error: Cannot find Sofia-SIP - looked for sofia-config and libsofia-sip-ua in /usr/local

**Comment by seven1240** [comment]
we cannot help you before you can give us more information. see #7 . Reopen if you still think it's a problem and ready to give us more infromation.
